openapi: 3.0.0
info:
  title: EcoHarvest APIs
  version: 1.0.0
  description: API for user authentication
servers:
  - url: https://ecoharvest.onrender.com
paths:
  /:
    get:
      summary: Server Status
      responses:
        '200':
          description: 'Server Health'
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: true
                  status:
                    type: string
                    description: normal
                  message:
                    type: string
                    description: Service is Up
  /api/v1/auth/login:
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT token for accessing protected resources
        '401':
          description: Unauthorized - Invalid credentials
        '404':
          description: User is not Registered with Us Please SignUp to Continue
  /api/v1/auth/signup:
    post:
      summary: User Signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: User's name
                email:
                  type: string
                  description: User's email
                password:
                  type: string
                  format: password
                  description: User's password
                confirmPassword:
                  type: string
                  format: password
                  description: User's password
                otp:
                  type: string
                  description: OTP sent to email address
      responses:
        '200':
          description: User Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT token for accessing protected resources
        '400':
          description: Missing Fields
        '422':
          description: Password and Confirm Password Must be same.
        '401':
          description: Unauthorized - Invalid OTP
        '409':
          description: User already exists. Please sign in to continue.
  /api/v1/auth/send-otp:
    post:
      summary: Send Otp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email
      responses:
        '200':
          description: OTP send Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT token for accessing protected resources
        '401':
          description: Unauthorized - User already Exists